Mall Customers Data Analysis
Import Libraries and Load Dataset

In [37]:
import numpy as np
import pandas as pd

df=pd.read_csv(r"C:\Users\Admin\Downloads\Mall_Customers.csv")
df.head()

   CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)
0           1    Male   19                  15                      39
1           2    Male   21                  15                      81
2           3  Female   20                  16                       6
3           4  Female   23                  16                      77
4           5  Female   31                  17                      40

Viewing the last five rows

In [9]:
df.tail()

     CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)
195         196  Female   35                 120                      79
196         197  Female   45                 126                      28
197         198    Male   32                 126                      74
198         199    Male   32                 137                      18
199         200    Male   30                 137                      83

Checking Dataset Dimensions
Rows represent customers.
Columns represent customer attributes.

In [10]:
df.shape

(200, 5)

Checking Column Names
The columns attribute displays the names of all columns present in the dataset.

In [11]:
df.columns

Index(['CustomerID', 'Gender', 'Age', 'Annual Income (k$)',
       'Spending Score (1-100)'],
      dtype='str')

Checking Data Types

The dtypes attribute shows the data type of each column. This helps us understand which columns contain numerical data and which contain categorical data.

In [12]:
df.dtypes

CustomerID                int64
Gender                      str
Age                       int64
Annual Income (k$)        int64
Spending Score (1-100)    int64
dtype: object

Dataset Information

The info() function provides a summary of the dataset

In [13]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 5 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   CustomerID              200 non-null    int64
 1   Gender                  200 non-null    str
 2   Age                     200 non-null    int64
 3   Annual Income (k$)      200 non-null    int64
 4   Spending Score (1-100)  200 non-null    int64
dtypes: int64(4), str(1)
memory usage: 7.9 KB

Statistical Summary

In [14]:
df.describe()

       CustomerID         Age  Annual Income (k$)  Spending Score (1-100)
count  200.000000  200.000000          200.000000              200.000000
mean   100.500000   38.850000           60.560000               50.200000
std     57.879185   13.969007           26.264721               25.823522
min      1.000000   18.000000           15.000000                1.000000
25%     50.750000   28.750000           41.500000               34.750000
50%    100.500000   36.000000           61.500000               50.000000
75%    150.250000   49.000000           78.000000               73.000000
max    200.000000   70.000000          137.000000               99.000000

Finding the Average Age

In [15]:
df["Age"].mean()

np.float64(38.85)

Finding Unique Income Values

Finding Unique Age Values

In [16]:
df["Age"].unique()

array([19, 21, 20, 23, 31, 22, 35, 64, 30, 67, 58, 24, 37, 52, 25, 46, 54,
       29, 45, 40, 60, 53, 18, 49, 42, 36, 65, 48, 50, 27, 33, 59, 47, 51,
       69, 70, 63, 43, 68, 32, 26, 57, 38, 55, 34, 66, 39, 44, 28, 56, 41])

Counting Unique Income Value

In [17]:
df["Annual Income (k$)"].unique()

array([ 15,  16,  17,  18,  19,  20,  21,  23,  24,  25,  28,  29,  30,
        33,  34,  37,  38,  39,  40,  42,  43,  44,  46,  47,  48,  49,
        50,  54,  57,  58,  59,  60,  61,  62,  63,  64,  65,  67,  69,
        70,  71,  72,  73,  74,  75,  76,  77,  78,  79,  81,  85,  86,
        87,  88,  93,  97,  98,  99, 101, 103, 113, 120, 126, 137])

Frequency of Spending Scores

This helps identify the most common spending scores

In [18]:
df["Annual Income (k$)"].nunique()

64

Checking Missing Values

In [19]:
df["Spending Score (1-100)"].value_counts()

Spending Score (1-100)
42    8
55    7
73    6
46    6
35    5
     ..
68    1
85    1
23    1
8     1
18    1
Name: count, Length: 84, dtype: int64

The sum() function counts the number of missing values in each column.

In [20]:
df.isnull()

     CustomerID  Gender    Age  Annual Income (k$)  Spending Score (1-100)
0         False   False  False               False                   False
1         False   False  False               False                   False
2         False   False  False               False                   False
3         False   False  False               False                   False
4         False   False  False               False                   False
..          ...     ...    ...                 ...                     ...
195       False   False  False               False                   False
196       False   False  False               False                   False
197       False   False  False               False                   False
198       False   False  False               False                   False
199       False   False  False               False                   False

[200 rows x 5 columns]

Calculating Missing Value Percentage

In [21]:
df.isnull().sum

<bound method DataFrame.sum of      CustomerID  Gender    Age  Annual Income (k$)  Spending Score (1-100)
0         False   False  False               False                   False
1         False   False  False               False                   False
2         False   False  False               False                   False
3         False   False  False               False                   False
4         False   False  False               False                   False
..          ...     ...    ...                 ...                     ...
195       False   False  False               False                   False
196       False   False  False               False                   False
197       False   False  False               False                   False
198       False   False  False               False                   False
199       False   False  False               False                   False

[200 rows x 5 columns]>

Checking for Duplicate Records

In [22]:
df.isnull().mean()*100

CustomerID                0.0
Gender                    0.0
Age                       0.0
Annual Income (k$)        0.0
Spending Score (1-100)    0.0
dtype: float64

selects the first five rows of the dataset

In [23]:
df.duplicated().sum()

np.int64(0)

selects the first five rows of the dataset

In [24]:
df.iloc[0:5]

   CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)
0           1    Male   19                  15                      39
1           2    Male   21                  15                      81
2           3  Female   20                  16                       6
3           4  Female   23                  16                      77
4           5  Female   31                  17                      40

Filtering Data

we select customers whose age is less than 20

In [25]:
df[df["Age"]<20]

     CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)
0             1    Male   19                  15                      39
33           34    Male   18                  33                      92
61           62    Male   19                  46                      55
65           66    Male   18                  48                      59
68           69    Male   19                  48                      59
91           92    Male   18                  59                      41
111         112  Female   19                  63                      54
113         114    Male   19                  64                      46
114         115  Female   18                  65                      48
115         116  Female   19                  65                      50
138         139    Male   19                  74                      10
162         163    Male   19                  81                       5

Sorting the Dataset

customers are sorted according to their Spending Score in ascending order

In [26]:
df.sort_values("Spending Score (1-100)")

     CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)
156         157    Male   37                  78                       1
158         159    Male   34                  78                       1
8             9    Male   64                  19                       3
30           31    Male   60                  30                       4
32           33    Male   53                  33                       4
..          ...     ...  ...                 ...                     ...
167         168  Female   33                  86                      95
185         186    Male   30                  99                      97
145         146    Male   28                  77                      97
19           20  Female   35                  23                      98
11           12  Female   35                  19                      99

[200 rows x 5 columns]

Renaming Columns

the Age column is renamed to Age in years to make its meaning clearer

In [27]:
df.rename(columns={"Age":"Age in years"})

,CustomerID,Gender,Age in years,Annual Income (k$),Spending Score (1-100)
0,1,Male,19,15,39
1,2,Male,21,15,81
2,3,Female,20,16,6
3,4,Female,23,16,77
4,5,Female,31,17,40
...,...,...,...,...,...
195,196,Female,35,120,79
196,197,Female,45,126,28
197,198,Male,32,126,74
198,199,Male,32,137,18
199,200,Male,30,137,83

Creating a New Column

Annual Income is given in thousands of dollars (k$)

In [28]:
df["Annual Income ($)"] = df["Annual Income (k$)"] * 1000

Viewing Data Except the Last 15 Rows

In [29]:
df.head(-15)

,CustomerID,Gender,Age,Annual Income (k$),Spending Score (1-100),Annual Income ($)
0,1,Male,19,15,39,15000
1,2,Male,21,15,81,15000
2,3,Female,20,16,6,16000
3,4,Female,23,16,77,16000
4,5,Female,31,17,40,17000
...,...,...,...,...,...,...
180,181,Female,37,97,32,97000
181,182,Female,32,97,86,97000
182,183,Male,46,98,15,98000
183,184,Female,29,98,88,98000
184,185,Female,41,99,39,99000

Groups by Gender, finds average spending score

In [30]:
df.groupby("Gender")[["Annual Income (k$)", "Spending Score (1-100)"]].mean()

        Annual Income (k$)  Spending Score (1-100)
Gender
Female           59.250000               51.526786
Male             62.227273               48.511364

Removing an Unnecessary Column

The Annual Income ($) column was created temporarily for conversion purposes

In [31]:
df = df.drop(columns=["Annual Income ($)"])

In [32]:
df.tail()

     CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)
195         196  Female   35                 120                      79
196         197  Female   45                 126                      28
197         198    Male   32                 126                      74
198         199    Male   32                 137                      18
199         200    Male   30                 137                      83